language: java
addons:
  sonarcloud:
    organization: fscotto
    token:
      secure:
        secure: T2oSGvt9yEI+Nnxc5Eyjqcmv7f+jNBW9t2Vwr9mVvEfmK7hl2oYDkjOgaaqxEX2EClZUtAZpnJEO8V07YvrFK/m2VZ9gIra+e8NCzGIP/c4oQL2DrZJMim5RJZJvskUK6Kuq650xLlYYPY5j5C9r8JprmiU6ftNIMCVWLgpJxKX/hLFISwsi0qW6e4ny41IVObd6BVosGu0pkFbeqaY88ZFn1UYPbfhQ77J6qaIrN5PWs4SI1c2/FX2fY2NrmUBTcmt1t59YwrQFi0DTAfIbbNbrCFoHmTWEm6GSATHTFwGNvUyOOVJW+a1mUZt3UvTCtjZD5hXZfeqhFDxYOOPKqXiiFXEpbavfqBpHVxXywCB8IuV4eQrDfuVt2txdCxMb7eTPzf518EnmwUjBbfU4PWFZPJhvgMckXxpsGJ6skn6g7Dr+bZzznB24cuSzo0Xq0yE96wpshIysn+2BH5AeKjUk6qTSAs9asdy1KhUg0A5W967jIs8GhBbhNW/NAMKGSIhAwLsoxNW+6DPs2u3NRF3kUI6bTbiYMf8hqArA0M/EHD0SOQhVehe7qtHgwROXagn7vRE57V5j+tibo2DqKkCNa1ymKqxHxYFK8q5p+E7FGBy3MreC82vrOn6pzhDnQfR1Ywo/K3ZSWjkFuu48RrBUd5qHN2CSKASLwGI2feU=
script:
  - sonar-scanner
deploy:
  provider: heroku
  api_key:
    secure: BdLP42kNH69e7MqjKrsK+ZfqC5QJHtVLK7IKIEi01NpWcw6vgRs5cx0VosEnPIXBXT8PsQm5M9EOaT/6zlMt6li5p3OSIhXkwaEBuXPK+aOwvK9R2CXkFIDaSwNPPyNJvBgHXrpfLr/V+6W1fZW8eQM6sF4kmZtB9TU9QYfLvn9LmGiU4jYPGmqruCXZlW3s8bYauRFw8XY7XuEKicBDkPZBXOPKltUebxGsPHvwFoW5oIbWWqQ58JzF6cgrclu76rlaEQ9hT/5m5Q0EY/O9WUn0mU3wajvlglvjx7mmY1vwJlSpu+I2a3u1EwBsYHpQj8YhTEQr4Tv4wpkNJX+CuNpUUL3czsfUvm/jLZZ2Wczu9Xz2xo/9nESEL3W63gY5Jv1aQYZ7PlQjmBwSG9HEsfm55NEOLkSs9SqyA3PgzNyQ7uxgvV7owVBPtQR5jC42d0Xvze48bRDzzl62vqM0/O3qxLPq01+vSJi61SoOcXbwSxtUN2VkbAGsvfGl8swhaBEULe9hotJ3h5LyxPe/GrMcw0RWzqM2St9tIdHWhHCWTZ+8tUUzQEqVshuybWhCVkMAV9TGwpLb9PdyQ5ShUVapkYwW/6uIUw8rvfLRcp5h4O/YzvqxjYXdoSGdSGPUhCN/KTMx7bjSfLnghZawdQgq4cWlK15InUduYpk6zq8=
  app: powerful-bayou-38465
jdk:
- openjdk11
