language: java
deploy:
  provider: heroku
jdk:
- openjdk11
81175cb5-50f5-46ce-a8ff-3455c1166d15:
  secure: SKmI8lX69a4fGuJ6tg9thy7pNl0DFSGj6gpRIZZRdHcbAGREY7ygjdBBSz1xew6kRWRHUHkSDiyZXR0hs1pZNzil7c46z6sc1OXqdJT6iYh7ZpSBzj608PyzZcABfioljzr8fr8HkVUV3qcnM6Xs6rHRj10OxROq+gv/7CJhm6Q0X6YcGFspJymR9fmFh802/jSY3zSnfGJM3ag5wDw0qxMO0GtWkYAFdrTeFDxxD8Ey+iWGuyLBriBmOXwKpqzJfj6t/RSzS+vkd2ouDqLRmmMdGZyDO+xV0FwNhEzeo+5Iq+ZvbnI2NQwmZJQ6sgipc7/ajHrHrPTMZzYRTj84C7DaCYyjHoN0467to23jkxyd6rNkR3i6oVE+3N3xAalLlIndW7b0LNYMu2sFoLXKD0/vse5VAbgwMkdHzHjoE6EVx7uupNU7Ib0TEXjCplPSHQ5DH2FvL9Ha5o2fbg/cQruPTJvs0WYQtcSnUUU7hU47d9QlbfcoP0n8FFqEaMZPZB2MD+s27BBdHqVq22JNrwEf6V9AiaOadfy+kwmrNQhBCe42sldGB1+68gZNnYovs9MelGwhC5kuTOkfB24kFwwshwQZHNpTXhTzQ4npCjYKhpYmnk4/g2oxDhC7Zp5Cf9sOLCFAfo+7zeZKyt7yKhel0BipgNI4fPpXQbT/nEE=
